### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by shinnn**
- Use [arrify](https://github.com/sindresorhus/arrify) to simplify conditional branching
- Remove [async.js](https://github.com/caolan/async)
  - [`async.waterfall`](https://github.com/caolan/async#waterfall) is actually not needed because the really asynchronous task is only API access and all the rest of tasks are synchronous.

### CODE REVIEW

**Comment by shinnn** [comment]
Could you [add me to this project as a collaborator](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/) and give owner access to [the npm package](https://www.npmjs.com/package/hubot-weather-ja)? I'd like to help maintaining this project.

**Comment by shinnn** [comment]
@ryurock Any updates?

**Comment by ryurock** [comment]
gj! thanks!

**Comment by ryurock** [comment]
I welcome shinnn as maintainer of this project
added collaborator

**Comment by shinnn** [comment]
Great! Thanks, @ryurock :)

**Pull request merged**
